### ISSUE TITLE
Remote repository is not configured or is incorrect

### ISSUE THREAD

**Issue by micah** [sigma/magit-gh-pulls#11]
Hello,

I am trying to use this but am unsure what I need to configure for the remote repository to have it work. I tried doing: git config magit.gh-pulls-repo=git@github.com:leapcode/leap_platform.git in a repository, but when I do # g g in magit-status, it tells me "Remote repository is not configured or incorrect".

**Comment by alexander-yakushev** [comment]
Marking as fixed as the original issue was apparently resolved.
