### ISSUE TITLE
fetching commits uses 'git:' protocol, not https

### ISSUE THREAD

**Issue by warner** [sigma/magit-gh-pulls#13]
When I used `# g f` just now (commit 1f310b0), the `*magit-process*` buffer reported that the `git fetch` command it ran was using a repo URL of `git://github.com/pyca/pynacl.git`. I was hoping it would use `https://github.com/pyca/pynacl.git`, which benefits from TLS authentication of the received data. The raw `git:` protocol is *not* authenticated, so a network attacker could substitute the wrong source code for the branch contents.

I think that this could be fixed by changing `magit-gh-pulls-fetch-commits` to use the `:html-url` property instead of the `:git-url` property, or by changing `gh.el` to add an `:https-url` property (which, for github, would be equal to `:html-url` plus `.git`) and then magit-gh-pulls could use that.

**Comment by channikhabra** [comment]
My ISP blocks `git:` protocol (actually ssh to github on default port, I have to use ssh.github.com on port 443), so fetching commits just hang and fail eventually.

**Comment by mgalgs** [comment]
As @tarsius eluded, an `insteadOf` config does the trick when working with private repos.  Specifically, something like:

    $ git config url.git@github.com:.insteadOf git://github.com/

**Comment by alexander-yakushev** [comment]
Does anyone still have any problems with this? I just tried cloning a private repo via SSH and was able to fetch commits for pull requests without any additional configuration.

**Comment by nwolfe** [comment]
> Does anyone still have any problems with this?

Yes, I am still unable to pull from private repos.  I have not tried the workaround mentioned above.  Using the SSH protocol works though.  We should improve this behavior if we can!

**Comment by alexander-yakushev** [comment]
Thanks for the response, @nwolfe!

How did you "switch" to SSH protocol? And how is the remote to your project written? Is it `git@github.com:username/project.git`?

**Comment by nwolfe** [comment]
> How did you "switch" to SSH protocol?

I didn't switch magit, I just ran the `git fetch git@github...` command manually outside of Emacs.

> And how is the remote to your project written? Is it `git@github.com:username/project.git`?

Yes, that is the format that works for me (to pull from private repos).

---

> I have not tried the workaround mentioned above.

I'm currently trying to get the `git config url.git@github.com:.insteadOf git://github.com` workaround working as a global thing configuration so I don't have to do that for every private repo/remote that I work with.  So far no such luck.  Might try customizing the magit-gh-pulls fetch command directly in Emacs next.

**Comment by alexander-yakushev** [comment]
magit-gh-pulls does all Github interoperation through another library, [gh.el](https://github.com/sigma/gh.el). What confuses me is that I'm able to work with my private repos just fine without using any workarounds. I wonder what is different between our setups.

**Comment by alexander-yakushev** [comment]
> Yes, that is the format that works for me (to pull from private repos).

But is that what says in your `.git/config` file?

**Comment by nwolfe** [comment]
> What confuses me is that I'm able to work with my private repos just fine without using any workarounds.

Is it because they're *your* private repos (i.e. your github user)?  Not sure, just asking.

> I wonder what is different between our setups.

I'm hoping to find something workable in the Emacs code, maybe some configuration setting to control this globally from there rather than in `.git/config` files.

**Comment by nwolfe** [comment]
> But is that what says in your .git/config file?

Yes that is the format specified in my config files as well.

**Comment by alexander-yakushev** [comment]
Wait, I think I'm just being incredibly stupid...

**Comment by nwolfe** [comment]
@alexander-yakushev Your fix in https://github.com/sigma/magit-gh-pulls/commit/37c9f2a3dd13cd0fe4f810f078e64ad3d108073c seems to have done the trick! I am able to fetch commits from pull requests against private repositories. Thank you :sunny:

**Comment by alexander-yakushev** [comment]
@nwolfe Good to know!

@mgalgs If you still use magit-gh-pulls, could you please confirm this now works for you too?

**Comment by mgalgs** [comment]
Works for me! Thanks!

**Comment by alexander-yakushev** [comment]
Great! Thanks everyone!
