### ISSUE TITLE
pull request face colour is messed up on fold toggle

### ISSUE THREAD

**Issue by chalmagean** [sigma/magit-gh-pulls#16]
Using <TAB> to toggle folding seems to mess up the colours.

![magit](https://cloud.githubusercontent.com/assets/8421/4122380/d40ffcfc-32c3-11e4-9e90-10d3a1857de1.png)

**Comment by alexander-yakushev** [comment]
I had a similar problem and it turned out it was related to `font-lock-mode` being enabled in Magit buffers. Can you confirm that you still have this isue?

**Comment by alexander-yakushev** [comment]
@chalmagean Can you please confirm if you still have this issue and whether you still use magit-gh-pulls? Thanks.

**Comment by chalmagean** [comment]
I don't have a way of testing that anymore, sorry.

**Comment by alexander-yakushev** [comment]
OK, no problem.
