### ISSUE TITLE
is the canonical upstream sigma/* or magit/*?

### ISSUE THREAD

**Issue by tarsius** [sigma/magit-gh-pulls#3]
You forked `magit-gh-pulls` to the `magit` organisation. Now I am unsure which repository should be considered the canonical upstream. Other people might have the same problem.

To me it would make sense for the `magit/magit-gh-pulls` to be the official repository, like it is done for other "organisations" like `helm`. If you agree the best way to do that would be:

1. Delete `magit/magit-gh-pulls`.
2. "Transfer" the repository from `sigma` to `magit` (at https://github.com/sigma/magit-gh-pulls/settings)
3. (Possibly) fork `magit/*` to `sigma/*` again.

Now `sigma` is a fork of `magit`. The reason why you should transfer the repository from `sigma` to `magit` is that this causes forks of `sigma` will become forks of `magit`. If you instead just deleted `sigma` (and then possibly forked it from `magit`) all former forks would become "original repositories" that aren't forks of anything (according to github). Also existing issues and pull requests won't be lost if you do it the way I suggested.

There are currently no forks of `magit/magit-gh-pulls`.

The same applies to `org-magit`.

**Comment by alexander-yakushev** [comment]
@tarsius Now that 2.1 is solid, and magit-gh-pulls works with it, can we bring the transfership question up again?

**Comment by tarsius** [comment]
I would rather not because I intend to write a replacement.

**Comment by alexander-yakushev** [comment]
Oh, I see. Less work for me than :D.

**Comment by tarsius** [comment]
... but it will take a while. So you should still keep this in good shape :-)
