### ISSUE TITLE
create pull request functionality seems broken! 

### ISSUE THREAD

**Issue by robbyoconnor** [sigma/magit-gh-pulls#35]
I am unable to create a PR via `magit-gh-pulls` 

it grabs the Title, Description and then I get:

```
Contacting host: api.github.com:443
menu-bar-update-yank-menu: Wrong type argument: stringp, nil

```

**Comment by alexander-yakushev** [comment]
Are you sure about that? I get this message if I try to make a pull request from the same branch of the same remote. When creating a valid pull request (that has differing commits, and all of them are pushed to github) it works.

**Comment by robbyoconnor** [comment]
Ah, maybe make the error messages a bit clearer...it's still a bug in my opinion -- even if the original premise of the bug has changed..

**Comment by robbyoconnor** [comment]
I just tested this -- what I think could be a sane way of handling this (my elisp-fu is good enough to do basic things but falls apart when things get complex...but display an error in this case...I'm closing this.
