### ISSUE TITLE
Does not play nice with evil

### ISSUE THREAD

**Issue by robbyoconnor** [sigma/magit-gh-pulls#36]
This does not play well with evil.

I get 
```
byte-code: Key sequence j q starts with non-prefix key j
```

The [offending line](https://github.com/sigma/magit-gh-pulls/blob/master/magit-gh-pulls.el#L420)  is:
```elisp
(define-key magit-status-mode-map (kbd "jq") 'magit-jump-to-pulls)
```

**Comment by alexander-yakushev** [comment]
`magit-gh-pulls` uses the same convention for that binding as Magit. See magit/magit#1978. For example `ju` or `jp`. Do you have problems with those bindings too?

**Comment by syl20bnr** [comment]
Unfortunately this is very specific to spacemacs and the current `jq` bindings makes sense.
The issue with spacemacs is that for Vim users, `j` is bound to `next-line` which overwrite the prefix command and thus gives an error when initializing `magit-gh-pulls`.

`jq` is perfectly valid and modify it just for spacemacs would be stupid so you can close this PR, we will find some good hackery to make it work in spacemacs :-)

**Comment by robbyoconnor** [comment]
I'm going to close this

**Comment by alexander-yakushev** [comment]
@syl20bnr Thank you for clearing this up. I assumed this is Evil-related, but anyway it should be solved on a higher level, either in Magit or Evil. If at any point Magit changes their `j_` bindings, I will change this one too.
