### ISSUE TITLE
Ability to diff a PR 

### ISSUE THREAD

**Issue by adamdecaf** [sigma/magit-gh-pulls#40]
So I noticed that you can go to the last commit on a PR and diff that `d r` works to diff the current branch **against** the remote branch. However, that shows the inverse of the diff. So is there an easier way to set the remote branch (which is hard to find) as the base and diff master against it? e.g. to invert the `d r` logic? 

Or perhaps I'm missing something on a better way to diff PR's inside this.

**Comment by alexander-yakushev** [comment]
@adamdecaf I've just pushed this as a new feature. You can now do `# d` when highlighting the PR, and it will show the whole diff between the last commit in PR and the base commit of the PR. Is this the behavior you would expect from this feature?

**Comment by adamdecaf** [comment]
@alexander-yakushev Yea, that's what I was looking for. Thanks!
