### ISSUE TITLE
Default PR summary to first commit's summary

### ISSUE THREAD

**Issue by stig** [sigma/magit-gh-pulls#41]
We use some approximation of git flow, so we often use single-commit PRs to get benefit from various bots watching PRs and commenting on them. (codecov, static analysis, lint, etc, RFC from coworkers etc). 

Even in a multi-commit PR the first commit's summary usually conveys the intent of the PR. (In my experience, at least.) Thus I often end up manually duplicating the summary of the first commit in the PR as the PR summary.

**Comment by alexander-yakushev** [comment]
@thieman Did this close because you've wrote `Closes #41` in your PR? I didn't know one can do that. Looks neat, but might be abused too, I suppose.

**Comment by thieman** [comment]
Yup, if a PR gets merged with "Closes #x" or "Fixes #x" in the body, it'll automatically close the referenced issue.

**Comment by alexander-yakushev** [comment]
Hm, alright, thanks. Sounds convenient. Still, I would limit that only to closing the issues one created themselves.
