### ISSUE TITLE
magit popup integration

### ISSUE THREAD

**Issue by blaenk** [sigma/magit-gh-pulls#44]
I'm pretty sure that it's possible to hook into the magit pop up system so that we can easily drill-down on the various actions available in this plugin, which admittedly aren't many, but it'd be nice to have a complete experience nonetheless.

**Comment by stig** [comment]
+1

**Comment by aspiers** [comment]
+1

**Comment by alexander-yakushev** [comment]
@blaenk I've just pushed commits that introduce `magit-popup` mechanism to control magit-gh-pulls. It is invoked by pressing `#`. Please give it a look and tell me how it works for you, thanks!

**Comment by alexander-yakushev** [comment]
This has been working fine for a while now, guess it's time to close!
