### ISSUE TITLE
Better keyboard shortcuts

### ISSUE THREAD

**Issue by aspiers** [sigma/magit-gh-pulls#51]
When the point is on a pull request line in the magit status buffer, it should be possible to use single keystrokes to invoke actions on the pull request, and these should be consistent with magit's standard keyboard shortcut conventions.  For example I would suggest the following:

- `f` invokes `magit-gh-pulls-fetch-commits`
- `SPC` opens a log buffer which starts at the head of the PR branch
- `RET` does the same but also switches the point to the log buffer
- `b b` would check out the PR branch as a detached head
- `b B` would allow you to create a local branch pointing to the head of the PR branch

**Comment by alexander-yakushev** [comment]
That's a considerable idea. But right now I'm thinking of changing `# g` prefix just to `#`, and making a magit-like popup menu for it. Do you think that should be enough (like doing `# f` to fetch a PR)? I don't really want to introduce one-key bindings like `f` because at some point Magit might need them too.

**Comment by aspiers** [comment]
+1 for `#` -> `# g`, and +100 for making it a popup menu :-)

I had thought that Magit allowed context-sensitive trapping of its own shortcuts like `f` but I probably just wrongly imagined that - if so I guess that would need a feature request against magit (which of course might get rejected for valid reasons, I'm not sure).

/cc @tarsius

**Comment by alexander-yakushev** [comment]
@aspiers I've just pushed commits that introduce `magit-popup` mechanism to control magit-gh-pulls. It is invoked by pressing `#`. Consequently all keybindings lose `g` in the middle. Please give it a look and tell me how it works for you.

**Comment by stig** [comment]
The magit-popup menu is very nice :-)

**Comment by aspiers** [comment]
@alexander-yakushev It's awesome, thanks so much :)
