### ISSUE TITLE
Using the refs/pull/* namespace for fetching objects

### ISSUE THREAD

**Issue by mgalgs** [sigma/magit-gh-pulls#58]
I've seen a few cases working on private repos (with private forks) where magit-gh-pulls tries to fetch things over `git://`.  This doesn't work for private repos so I'm unable to fetch commits for those PRs.

Seems like it would be simpler to fetch objects for a given PR using github's `refs/pull/*` namespace.  The URL for fetching objects for any PR is simply the URL of the "origin" (or what have you) remote, but using the ref: `refs/pull/<pr_num>/head`.  No need to traverse any APIs to find the URL of the fork, etc.  

Besides simplifying the remote URL code, this should fix instances where we try to fetch from private repos over `git://`, since we'll be fetching from our own repo, not a fork.

**Comment by alexander-yakushev** [comment]
So, basically, this is #13. I agree that this is necessary but unfortunately I don't have time right now to implement/test/verify this. I welcome anyone else to try, and submit a PR, though.

**Comment by mgalgs** [comment]
As of 37c9f2a3dd13cd0fe4f810f078e64ad3d108073c we're fetching over ssh.
