### ISSUE TITLE
attach to magit-dispatch-popup

### ISSUE THREAD

**Issue by blaenk** [sigma/magit-gh-pulls#84]
Thanks for #44, I don't know how I missed your follow-up on it.

However, I also meant that gh-pulls should attach to the `magit-dispatch-popup`, or provide an easy way to do it.

I've done it myself by doing:

``` elisp
    (magit-define-popup-action 'magit-dispatch-popup
      ?# "Pull requests" 'magit-gh-pulls-popup ?!)
```

Here's what it looks like:

![popup](http://i.imgur.com/9Xdp3l0.png)

**Comment by waisbrot** [comment]
I see that PierreTechoueyres made PR #101 to provide this. It would be nice to have!

**Comment by alexander-yakushev** [comment]
#101 merged. Thanks for reporting!
